name: "Secure Checkout"
description: "Applies StepSecurity Harden-Runner and checks out the repository"

inputs:
  egress-policy:
    description: "Audit or Block"
    required: false
    default: "audit"

runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
      with:
        egress-policy: ${{ inputs.egress-policy }}

    - name: Checkout Code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        persist-credentials: false
