package repo

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

// Every Deployment, StatefulSet, DaemonSet, Job and CronJob written out in the
// repository is sized, placed and given a priority - found by walking the
// repository, not by a list somebody keeps (#492).
//
// The HelmRelease table above covers charts, and was the only guard. A plain
// manifest could not be expressed in it and was simply absent: the Valheim
// server shipped with no priority class, so it was priority zero, and with
// nothing keeping an 8 GiB pod off a 4 GiB control plane. Nothing said so,
// because a workload the guard had not been told about looked exactly like
// one with nothing wrong.
//
// So this finds every pod-producing document itself, and a file it cannot
// hold to the rules must be declared below with the reason - never skipped.

// Files whose workloads another guard, or nothing in this repository, owns.
var plainWorkloadsElsewhere = map[string]string{
	"clusters/management/flux-system/gotk-components.yaml": "the Flux controllers, generated by `flux bootstrap` and " +
		"held to these rules through the overlay's patches by TestEveryFluxControllerIsPlacedAndGivenAPriority",
	"clusters/bootstrap/cilium.yaml": "the CNI, rendered from its chart for Talos to apply before any node is Ready; " +
		"it runs on every node including the control planes by design, and nothing here edits its output",
}

var plainWorkloadKinds = map[string]bool{
	"Deployment": true, "StatefulSet": true, "DaemonSet": true, "Job": true, "CronJob": true,
}

type plainWorkload struct {
	file, kind, name string
	pod              map[string]any
}

func TestEveryPlainWorkloadIsSizedPlacedAndGivenAPriority(t *testing.T) {
	declared := declaredPriorityClasses(t)
	found := plainWorkloads(t)
	if len(found) == 0 {
		t.Fatal("found no plain workload anywhere, so this checked nothing - the game server alone should be one")
	}

	for _, w := range found {
		t.Run(w.file+"/"+w.name, func(t *testing.T) {
			what := fmt.Sprintf("%s %q in %s", w.kind, w.name, w.file)

			priority, _ := w.pod["priorityClassName"].(string)
			switch {
			case priority == "":
				t.Errorf("%s has no priority class, so it is priority zero - below every class this estate "+
					"declares, and the first thing preempted on a node it shares with CI.", what)
			case !declared[priority]:
				t.Errorf("%s names the priority class %q, which no manifest declares. A pod naming a class "+
					"that does not exist is refused admission, not given zero.", what, priority)
			}

			for _, list := range []string{"initContainers", "containers"} {
				containers, _ := w.pod[list].([]any)
				if list == "containers" && len(containers) == 0 {
					t.Fatalf("%s has no containers, so there is nothing to size", what)
				}
				for _, c := range containers {
					cm, _ := c.(map[string]any)
					name, _ := cm["name"].(string)
					if err := requestsAreComplete(t, cm["resources"]); err != nil {
						t.Errorf("%s: %s %q %s, so the pod is BestEffort and the OOM controller will "+
							"choose it first (#237)", what, strings.TrimSuffix(list, "s"), name, err)
					}
				}
			}

			// A DaemonSet runs everywhere on purpose; every other workload
			// stays off the machines holding quorum.
			if w.kind == "DaemonSet" {
				return
			}
			terms := requiredNodeSelectorTerms(t, w.pod)
			switch {
			case terms == nil:
				t.Errorf("%s has no required node affinity, so nothing keeps it off a control plane - "+
					"and a preferred one puts it back there when the workers are busiest.", what)
			case nodeAffinityAdmits(t, terms, aControlPlaneNode):
				t.Errorf("%s would schedule onto a control-plane node.", what)
			case !nodeAffinityAdmits(t, terms, aWorkerNode):
				t.Errorf("%s would not schedule onto a worker either, so its affinity takes it off the estate.", what)
			}
		})
	}
}

// plainWorkloads walks every manifest under the directories Flux and Talos
// read, and returns each pod-producing document that is a whole manifest -
// not a kustomize patch fragment, which carries only the fields it changes.
func plainWorkloads(t *testing.T) []plainWorkload {
	t.Helper()
	root := repoRoot(t)
	patches := kustomizePatchFiles(t, root)

	var out []plainWorkload
	for _, dir := range []string{"clusters", "environments", "modules"} {
		err := filepath.WalkDir(filepath.Join(root, dir), func(path string, d os.DirEntry, err error) error {
			if err != nil || d.IsDir() || !(strings.HasSuffix(path, ".yaml") || strings.HasSuffix(path, ".yml")) {
				return err
			}
			rel, _ := filepath.Rel(root, path)
			if _, owned := plainWorkloadsElsewhere[rel]; owned || patches[rel] {
				return nil
			}
			body, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			dec := yaml.NewDecoder(strings.NewReader(string(body)))
			for {
				var doc struct {
					Kind     string `yaml:"kind"`
					Metadata struct {
						Name string `yaml:"name"`
					} `yaml:"metadata"`
					Spec map[string]any `yaml:"spec"`
				}
				if dec.Decode(&doc) != nil {
					break
				}
				if !plainWorkloadKinds[doc.Kind] {
					continue
				}
				spec := doc.Spec
				if doc.Kind == "CronJob" {
					jt, _ := spec["jobTemplate"].(map[string]any)
					spec, _ = jt["spec"].(map[string]any)
				}
				tmpl, _ := spec["template"].(map[string]any)
				pod, _ := tmpl["spec"].(map[string]any)
				if pod == nil {
					t.Errorf("%s: %s %q has no pod template, so it cannot be checked", rel, doc.Kind, doc.Metadata.Name)
					continue
				}
				out = append(out, plainWorkload{rel, doc.Kind, doc.Metadata.Name, pod})
			}
			return nil
		})
		if err != nil {
			t.Fatalf("walking %s: %v", dir, err)
		}
	}
	return out
}

// kustomizePatchFiles is every file a kustomization names as a patch. Those
// hold only the fields they change, so they are not whole workloads.
func kustomizePatchFiles(t *testing.T, root string) map[string]bool {
	t.Helper()
	out := map[string]bool{}
	for _, dir := range []string{"clusters", "environments", "modules"} {
		_ = filepath.WalkDir(filepath.Join(root, dir), func(path string, d os.DirEntry, err error) error {
			if err != nil || d.IsDir() || filepath.Base(path) != "kustomization.yaml" {
				return err
			}
			body, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			var k struct {
				Patches []struct {
					Path string `yaml:"path"`
				} `yaml:"patches"`
				PatchesStrategicMerge []string `yaml:"patchesStrategicMerge"`
			}
			if err := yaml.Unmarshal(body, &k); err != nil {
				t.Errorf("parsing %s: %v", path, err)
				return nil
			}
			base := filepath.Dir(path)
			add := func(p string) {
				if p == "" {
					return
				}
				rel, _ := filepath.Rel(root, filepath.Join(base, p))
				out[rel] = true
			}
			for _, p := range k.Patches {
				add(p.Path)
			}
			for _, p := range k.PatchesStrategicMerge {
				add(p)
			}
			return nil
		})
	}
	return out
}

// Every file declared as owned elsewhere still exists, or the declaration is
// a hole with a reason attached to nothing.
func TestEveryPlainWorkloadExemptionNamesARealFile(t *testing.T) {
	root := repoRoot(t)
	for rel, why := range plainWorkloadsElsewhere {
		if strings.TrimSpace(why) == "" {
			t.Errorf("%s is exempted with no reason", rel)
		}
		if _, err := os.Stat(filepath.Join(root, rel)); err != nil {
			t.Errorf("%s is exempted from the plain-workload guard and no longer exists: delete the entry", rel)
		}
	}
}
