name: Deploy Infrastructure
on:
  push:
    branches: [main]
    tags: ["v*"]
    paths:
      - "environments/**/infrastructure/**"
      - "modules/infrastructure/**"

permissions:
  contents: read

jobs:
  apply:
    name: Apply OpenTofu
    runs-on: self-hosted
    environment: ${{ github.ref_type == 'tag' && 'production' || 'staging' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Determine Target Directory
        id: set-env

        env:
          REF_TYPE: ${{ github.ref_type }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          if [ "$REF_TYPE" == "tag" ]; then
            echo "DIR=environments/production/infrastructure/" >> "$GITHUB_ENV"
            echo "🚀 Deploying to Production (Tag: $REF_NAME)"
          else
            echo "DIR=environments/staging/infrastructure/" >> "$GITHUB_ENV"
            echo "🛠️ Deploying to Staging (Branch: main)"
          fi

      - name: Tofu Init
        run: tofu init
        working-directory: ${{ env.DIR }}

      - name: Tofu Apply
        run: tofu apply -auto-approve
        working-directory: ${{ env.DIR }}
